// Centralized FontAwesome icon mapping.
// Uses FontAwesome React component to render named icons.
// Usage: <Icon name="truck" size="lg" />

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { fab } from '@fortawesome/free-brands-svg-icons';

// Register entire FA libraries — safer than hand-picking missing/renamed icons.
library.add(fas, fab);

// Curated map of friendly name → icon object.
// We use this so the codebase uses semantic names instead of raw `faTruck` etc.
import {
  faTruck, faTruckMoving, faBox, faBoxes, faBoxesPacking, faPallet, faCouch, faMobile,
  faFlask, faWheatAwn, faTshirt, faCar, faSnowflake, faTruckPickup,
  faCarRear, faTemperatureLow, faCheck, faCircleCheck, faCircleXmark,
  faArrowRight, faArrowLeft, faArrowUp, faArrowDown, faChevronRight, faChevronLeft,
  faMagnifyingGlass, faSliders, faFilter, faXmark, faPlus, faMinus,
  faUser, faUsers, faUserPlus, faUserShield, faUserTie, faCrown, faStar, faStarHalfAlt, faShield,
  faShieldHalved, faBolt, faBoltLightning, faFire, faFireFlameCurved, faRocket,
  faPaperPlane, faComment, faCommentDots, faComments, faMessage,
  faBell, faBellSlash, faCircleExclamation, faTriangleExclamation,
  faPhone, faEnvelope, faLocationDot, faMapPin, faMapLocation, faMapLocationDot,
  faRoute, faRoad, faCompass, faGlobe, faCity, faBuilding, faWarehouse,
  faWeightScale, faCube, faCubes, faCalendar, faCalendarDays,
  faClock, faEye, faEyeSlash, faLock, faUnlock, faKey, faHashtag, faAt,
  faCoins, faWallet, faCreditCard, faMoneyBill, faMoneyBillWave, faReceipt, faCartShopping,
  faTag, faTags, faPercent, faGift, faGem, faTrophy,
  faCircle, faCircleDot, faCircleInfo, faCirclePlay, faCircleUser, faCircleHalfStroke,
  faHome, faHouse, faHouseChimney, faRightFromBracket, faRightToBracket,
  faBars, faGrip, faGripVertical, faGripHorizontal, faEllipsis, faEllipsisVertical, faGear,
  faPen, faPenToSquare, faTrash, faTrashCan, faRotate, faRefresh,
  faSpinner, faCircleNotch, faCheckDouble,
  faShare, faShareNodes, faCopy, faDownload, faUpload, faCloudArrowUp, faCloudArrowDown,
  faList, faListCheck, faListUl, faTableCells, faLayerGroup,
  faChartLine, faChartBar, faChartPie, faChartSimple, faArrowTrendUp,
  faImage, faCamera, faFile, faFolder, faFolderOpen,
  faCircleArrowRight, faCircleArrowLeft, faCircleChevronRight, faCircleChevronLeft, faCircleChevronDown, faCircleChevronUp,
  faInfo, faQuestionCircle, faLightbulb, faWandMagicSparkles,
  faLeaf, faTree, faSun, faMoon, faCloud, faPowerOff,
  faPlay, faPause, faStop, faForward, faBackward, faVolumeHigh, faVolumeXmark,
  faHeart, faHandshake, faBriefcase, faSuitcase, faInbox,
  faIdCard, faAddressCard, faAward,
  faPhoneVolume, faSquarePhone, faSquarePhoneFlip,
  faArrowRightToBracket, faArrowRightFromBracket,
  faAngleRight, faAngleLeft, faAngleUp, faAngleDown, faUpRightAndDownLeftFromCenter,
  faCaretRight, faCaretLeft, faCaretUp, faCaretDown, faChevronDown, faChevronUp,
  faSquare, faSquareCheck, faSquarePlus, faSquareMinus, faSquareXmark, faSquarePen,
  faGraduationCap, faBook, faBookmark, faNewspaper, faHighlighter,
  faWrench, faHammer, faToolbox, faBug, faShieldVirus,
  faOctagon, faHexagon, faDiamond,
  faUtensils, faAppleWhole, faBurger,
  faShirt, faGlasses, faMask,
  faDice, faChess, faPuzzlePiece,
  faMusic, faHeadphones, faMicrophone, faTv, faVideo, faFilm,
  faDumbbell, faPersonRunning, faPersonWalking, faAnchor,
  faMountain, faSnowman, faUmbrella, faFireExtinguisher, faTent,
  faSoap, faDroplet, faKitMedical, faTablet,
  faVial, faVirus, faDna,
  faMoneyCheck, faSackDollar, faPiggyBank, faHandHoldingDollar,
  faChartArea, faChartColumn,
  faSort, faSortUp, faSortDown,
  faPalette, faPaintbrush, faGauge, faGaugeHigh, faQrcode, faBarcode, faTruckFast, faTruckArrowRight, faMap, faToggleOn, faToggleOff, faPaperclip,
  faTruckFront, faLocationArrow, faLocationPin, faCheckCircle, faUserCheck, faUserCog, faUserGear, faUserPen, faUserSlash,
  faRotateRight, faCircle as faCircleAlt, faXmark as faXmarkAlt, faCar as faCarSolid, faInbox as faInboxAlt, faTruck as faTruckAlt, faBell as faBellAlt, faArrowUp as faArrowUpAlt, faArrowDown as faArrowDownAlt, faXmark as faXmarkAlt2, faEdit as faEditSolid, faComment as faCommentAlt,
} from '@fortawesome/free-solid-svg-icons';

import {
  faTelegram as faTelegramBrand, faWhatsapp, faViber, faInstagram, faFacebook, faFacebookF,
  faTwitter, faXTwitter, faYoutube, faTiktok, faSnapchat, faPinterest,
  faLinkedin, faLinkedinIn, faGithub, faGitlab, faBitbucket, faSlack, faDiscord, faSkype,
  faApple, faGoogle, faMicrosoft, faAmazon, faPaypal, faStripe, faCcVisa, faCcMastercard,
  faGooglePlay, faAppStore, faAppStoreIos, faWindows, faLinux, faUbuntu,
} from '@fortawesome/free-brands-svg-icons';

// Map: name → { icon, category } for use with <Icon name="..." />
export const ICON_MAP = {
  // Logo
  truck: { icon: faTruckMoving, category: 'solid' },
  'truck-front': { icon: faTruckFront, category: 'solid' },
  truckPickup: { icon: faTruckPickup, category: 'solid' },

  // Cargo
  box: { icon: faBox, category: 'solid' },
  boxes: { icon: faBoxes, category: 'solid' },
  pallet: { icon: faPallet, category: 'solid' },
  cube: { icon: faCube, category: 'solid' },
  cubes: { icon: faCubes, category: 'solid' },
  furniture: { icon: faCouch, category: 'solid' },
  phone: { icon: faMobile, category: 'solid' },
  flask: { icon: faFlask, category: 'solid' },
  wheat: { icon: faWheatAwn, category: 'solid' },
  shirt: { icon: faTshirt, category: 'solid' },
  carPart: { icon: faCar, category: 'solid' },
  'weight-scale': { icon: faWeightScale, category: 'solid' },
  package: { icon: faBox, category: 'solid' },
  packageSearch: { icon: faBoxesPacking, category: 'solid' },

  // Transport
  tent: { icon: faTruck, category: 'solid' },
  ref: { icon: faSnowflake, category: 'solid' },
  bort: { icon: faTruckPickup, category: 'solid' },
  container: { icon: faTruck, category: 'solid' },
  evakuator: { icon: faCarRear, category: 'solid' },
  izoterm: { icon: faTemperatureLow, category: 'solid' },
  any: { icon: faCheck, category: 'solid' },

  // Arrows
  arrowRight: { icon: faArrowRight, category: 'solid' },
  arrowLeft: { icon: faArrowLeft, category: 'solid' },
  arrowUp: { icon: faArrowUp, category: 'solid' },
  arrowDown: { icon: faArrowDown, category: 'solid' },
  chevronRight: { icon: faChevronRight, category: 'solid' },
  chevronLeft: { icon: faChevronLeft, category: 'solid' },
  chevronDown: { icon: faChevronDown, category: 'solid' },
  chevronUp: { icon: faChevronUp, category: 'solid' },
  circleArrowRight: { icon: faCircleArrowRight, category: 'solid' },
  circleArrowLeft: { icon: faCircleArrowLeft, category: 'solid' },

  // UI / actions
  search: { icon: faMagnifyingGlass, category: 'solid' },
  filter: { icon: faFilter, category: 'solid' },
  filterOff: { icon: faFilter, category: 'solid' },
  sliders: { icon: faSliders, category: 'solid' },
  close: { icon: faXmark, category: 'solid' },
  x: { icon: faXmark, category: 'solid' },
  xmark: { icon: faXmark, category: 'solid' },
  plus: { icon: faPlus, category: 'solid' },
  minus: { icon: faMinus, category: 'solid' },
  check: { icon: faCheck, category: 'solid' },
  checkCircle: { icon: faCircleCheck, category: 'solid' },
  checkCircleSolid: { icon: faCheckCircle, category: 'solid' },
  xmarkCircle: { icon: faCircleXmark, category: 'solid' },
  infoCircle: { icon: faCircleInfo, category: 'solid' },
  questionCircle: { icon: faQuestionCircle, category: 'solid' },
  warning: { icon: faTriangleExclamation, category: 'solid' },
  exclamation: { icon: faCircleExclamation, category: 'solid' },
  info: { icon: faInfo, category: 'solid' },
  refresh: { icon: faRefresh, category: 'solid' },
  rotate: { icon: faRotate, category: 'solid' },
  rotateRight: { icon: faRotateRight, category: 'solid' },
  spinner: { icon: faSpinner, category: 'solid' },
  loader: { icon: faCircleNotch, category: 'solid' },
  eye: { icon: faEye, category: 'solid' },
  eyeSlash: { icon: faEyeSlash, category: 'solid' },
  pen: { icon: faPen, category: 'solid' },
  edit: { icon: faPenToSquare, category: 'solid' },
  trash: { icon: faTrash, category: 'solid' },
  trashCan: { icon: faTrashCan, category: 'solid' },
  more: { icon: faEllipsisVertical, category: 'solid' },
  dots: { icon: faGripVertical, category: 'solid' },
  gear: { icon: faGear, category: 'solid' },
  bars: { icon: faBars, category: 'solid' },
  list: { icon: faListUl, category: 'solid' },
  grid: { icon: faTableCells, category: 'solid' },

  // User
  user: { icon: faUser, category: 'solid' },
  users: { icon: faUsers, category: 'solid' },
  userPlus: { icon: faUserPlus, category: 'solid' },
  userShield: { icon: faUserShield, category: 'solid' },
  userTie: { icon: faUserTie, category: 'solid' },
  crown: { icon: faCrown, category: 'solid' },
  star: { icon: faStar, category: 'solid' },
  shield: { icon: faShield, category: 'solid' },
  shieldCheck: { icon: faCheckCircle, category: 'solid' },
  shieldAlt: { icon: faShieldHalved, category: 'solid' },
  signOut: { icon: faRightFromBracket, category: 'solid' },
  signIn: { icon: faRightToBracket, category: 'solid' },
  home: { icon: faHouseChimney, category: 'solid' },

  // Boost / status
  bolt: { icon: faBolt, category: 'solid' },
  boltLightning: { icon: faBoltLightning, category: 'solid' },
  fire: { icon: faFire, category: 'solid' },
  fireAlt: { icon: faFireFlameCurved, category: 'solid' },
  rocket: { icon: faRocket, category: 'solid' },
  pin: { icon: faMapPin, category: 'solid' },
  highlight: { icon: faPalette, category: 'solid' },
  palette: { icon: faPalette, category: 'solid' },

  // Chat
  message: { icon: faMessage, category: 'solid' },
  messageMiddle: { icon: faMessage, category: 'solid' },
  comment: { icon: faComment, category: 'solid' },
  commentDots: { icon: faCommentDots, category: 'solid' },
  comments: { icon: faComments, category: 'solid' },
  paperPlane: { icon: faPaperPlane, category: 'solid' },
  paperclip: { icon: faPaperclip, category: 'solid' },
  bell: { icon: faBell, category: 'solid' },
  bellRing: { icon: faBell, category: 'solid' },
  bellOn: { icon: faBell, category: 'solid' },
  bellSlash: { icon: faBellSlash, category: 'solid' },

  // Contact
  phoneAlt: { icon: faPhone, category: 'solid' },
  phoneVolume: { icon: faPhoneVolume, category: 'solid' },
  mobile: { icon: faMobile, category: 'solid' },
  envelope: { icon: faEnvelope, category: 'solid' },
  telegram: { icon: faTelegramBrand, category: 'brand' },
  whatsapp: { icon: faWhatsapp, category: 'brand' },

  // Location
  location: { icon: faLocationDot, category: 'solid' },
  mapPin: { icon: faMapPin, category: 'solid' },
  mapMarked: { icon: faMapLocationDot, category: 'solid' },
  route: { icon: faRoute, category: 'solid' },
  road: { icon: faRoad, category: 'solid' },
  signpost: { icon: faRoute, category: 'solid' },
  compass: { icon: faCompass, category: 'solid' },
  globe: { icon: faGlobe, category: 'solid' },
  city: { icon: faCity, category: 'solid' },
  building: { icon: faBuilding, category: 'solid' },
  warehouse: { icon: faWarehouse, category: 'solid' },
  calendar: { icon: faCalendarDays, category: 'solid' },
  clock: { icon: faClock, category: 'solid' },
  hashtag: { icon: faHashtag, category: 'solid' },
  at: { icon: faAt, category: 'solid' },

  // Security
  lock: { icon: faLock, category: 'solid' },
  unlock: { icon: faUnlock, category: 'solid' },
  key: { icon: faKey, category: 'solid' },
  eyeOpen: { icon: faEye, category: 'solid' },
  eyeClosed: { icon: faEyeSlash, category: 'solid' },

  // Money / wallet
  coins: { icon: faCoins, category: 'solid' },
  wallet: { icon: faWallet, category: 'solid' },
  creditCard: { icon: faCreditCard, category: 'solid' },
  moneyBill: { icon: faMoneyBillWave, category: 'solid' },
  moneyBillWave: { icon: faMoneyBillWave, category: 'solid' },
  gift: { icon: faGift, category: 'solid' },
  gem: { icon: faGem, category: 'solid' },
  receipt: { icon: faReceipt, category: 'solid' },
  receiptText: { icon: faReceipt, category: 'solid' },
  tag: { icon: faTag, category: 'solid' },
  cartShopping: { icon: faCartShopping, category: 'solid' },

  // Special UI
  lightbulb: { icon: faLightbulb, category: 'solid' },
  sparkle: { icon: faWandMagicSparkles, category: 'solid' },
  leaf: { icon: faLeaf, category: 'solid' },
  gauge: { icon: faGauge, category: 'solid' },
  gaugeHigh: { icon: faGaugeHigh, category: 'solid' },
  chartLine: { icon: faChartLine, category: 'solid' },
  chartBar: { icon: faChartBar, category: 'solid' },
  chartPie: { icon: faChartPie, category: 'solid' },
  inbox: { icon: faInbox, category: 'solid' },
  share: { icon: faShareNodes, category: 'solid' },
  copy: { icon: faCopy, category: 'solid' },
  download: { icon: faDownload, category: 'solid' },
  upload: { icon: faUpload, category: 'solid' },
  circlePlay: { icon: faCirclePlay, category: 'solid' },
  angleRight: { icon: faAngleRight, category: 'solid' },
  angleLeft: { icon: faAngleLeft, category: 'solid' },
  angleDown: { icon: faAngleDown, category: 'solid' },
  angleUp: { icon: faAngleUp, category: 'solid' },
  caretDown: { icon: faCaretDown, category: 'solid' },
  caretUp: { icon: faCaretUp, category: 'solid' },
  circleInfo: { icon: faCircleInfo, category: 'solid' },
  circleCheck: { icon: faCircleCheck, category: 'solid' },
  circleXmark: { icon: faCircleXmark, category: 'solid' },
  diamond: { icon: faDiamond, category: 'solid' },
  award: { icon: faAward, category: 'solid' },
  trophy: { icon: faTrophy, category: 'solid' },
  shieldHalved: { icon: faShieldHalved, category: 'solid' },
  truckFront: { icon: faTruckFront, category: 'solid' },
  brush: { icon: faPaintbrush, category: 'solid' },
  qr: { icon: faQrcode, category: 'solid' },
  barcode: { icon: faBarcode, category: 'solid' },
  truckFast: { icon: faTruckFast, category: 'solid' },
  truckArrowRight: { icon: faTruckArrowRight, category: 'solid' },
  mapLocation: { icon: faMapLocation, category: 'solid' },
  mapMarkedAlt: { icon: faMapLocationDot, category: 'solid' },
  map: { icon: faMap, category: 'solid' },
  starHalf: { icon: faStarHalfAlt, category: 'solid' },
  pencil: { icon: faPen, category: 'solid' },
  arrowRotate: { icon: faRotate, category: 'solid' },
  userLarge: { icon: faCircleUser, category: 'solid' },
  userCircle: { icon: faCircleUser, category: 'solid' },
  toggleOn: { icon: faToggleOn, category: 'solid' },
  toggleOff: { icon: faToggleOff, category: 'solid' },
  listCheck: { icon: faListCheck, category: 'solid' },
  ban: { icon: faCircleXmark, category: 'solid' },
  layerGroup: { icon: faLayerGroup, category: 'solid' },
  arrowTrendUp: { icon: faArrowTrendUp, category: 'solid' },
  boltCircle: { icon: faBolt, category: 'solid' },
};

// Re-export raw icon objects for components that want to import directly.
export {
  faPalette,
  faTelegramBrand,
};
